services:
  - type: web
    name: youba-crypto-bot
    env: python
    plan: free
    buildCommand: ""
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 8028036634:AAFS_FjnPrzLw1B-qYp2l1VCoYJBcRcXiv8
